name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test
